export const WIDGET_THEME = {
  backgroundColor: '#0f1117',
  inputBackgroundColor: '#181b23',
  inputBorderColor: '#262a36',
  inputTextColor: '#f0f4f8',
  textColor: '#f0f4f8',
  secondaryTextColor: '#78829690',
  buttonBackgroundColor: '#f76808',
  buttonTextColor: '#ffffff',
  buttonSecondaryBackgroundColor: '#262a36',
  buttonSecondaryTextColor: '#f0f4f8',
  errorTextColor: '#ef4444',
  borderRadius: '8px',
  fontFamily: "ui-monospace, 'Cascadia Code', 'Fira Code', monospace",
  fontSize: '13px',
  fontWeight: 400,
  smallFontSize: '11px',
  smallFontWeight: 400,
  labelSpacing: '0.1em',
  inputVerticalPadding: '8px',
  inputHorizontalPadding: '12px',
  buttonVerticalPadding: '10px',
  buttonHorizontalPadding: '16px',
}
